### ISSUE TITLE
Update readme with CLI command / add a CLI command feature

### ISSUE THREAD

**Issue by mishasaggi** [danwild/text2json#1]
Currently the Readme example lists how to use this internally when running the app but not with the CLI command.

**Comment by danwild** [comment]
Fair comment. 

Commit [b7bbbb0](https://github.com/danwild/text2json/commit/b7bbbb0f1ad9f4c541ec1b0f82ee0f8aedeecc36) correctly defines the `text-2-json` script for global use, much like the existing examples.

So to install globally and use like a CLI tool:

```shell
npm install -g text-2-json
text-2-json --i=test/test.txt --o=test/output.json --h
```
